kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: chrome-service-test-runs
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: "Hello World!"
      type: string
  tasks:
    - name: clone-repository
      params:
      - name: url
        value: $(params.SNAPSHOT.source.git-url)
      - name: revision
        value: $(params.SNAPSHOT.source.revision)
      taskRef:
        params:
        - name: name
          value: git-clone
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:0bb1be8363557e8e07ec34a3c5daaaaa23c9d533f0bb12f00dc604d00de50814
        - name: kind
          value: task
        resolver: bundles

