apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: chrome-service-e2e-tests
  namespace: hcc-platex-services-tenant
spec:
  application: chrome-service
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/RedHatInsights/chrome-service-backend
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/integration-test-scenarios/tasks/chrome-service-e2e-integration-test.yaml
  params:
    - name: SNAPSHOT
      value: "$(params.SNAPSHOT)"
  contexts:
    - name: application
      description: Application to test
